import type { Audit } from "@/types";
import { CATEGORIES, SEVERITY } from "./constants";
import { sortBySeverity, formatDate } from "./utils";

/** Render an audit as a clean Markdown brief for sharing / pasting into docs. */
export function buildReportMarkdown(audit: Audit): string {
  const lines: string[] = [];
  lines.push(`# UX Audit — ${audit.name}`);
  lines.push(`**${audit.screen}** · ${formatDate(audit.createdAt)}`);
  lines.push("");
  lines.push(`**Overall score:** ${audit.overallScore}/100 (Grade ${audit.grade})`);
  lines.push(`**Lenses:** ${audit.scope.map((s) => CATEGORIES[s].label).join(", ")}`);
  lines.push("");
  lines.push(audit.summary);
  lines.push("");

  lines.push("## Scores by lens");
  audit.categoryScores.forEach((c) => {
    lines.push(`- ${CATEGORIES[c.category].label}: ${c.score}/100 — ${c.findings} issue(s)`);
  });
  lines.push("");

  lines.push("## Findings");
  const issues = sortBySeverity(audit.findings.filter((f) => f.severity !== "positive"));
  issues.forEach((f, i) => {
    lines.push(`### ${i + 1}. [${SEVERITY[f.severity].label}] ${f.title}`);
    lines.push(`*${CATEGORIES[f.category].label} · ${f.location} · ${f.effort} effort / ${f.impact} impact*`);
    lines.push("");
    lines.push(`- **Observation:** ${f.observation}`);
    lines.push(`- **Why it matters:** ${f.whyItMatters}`);
    lines.push(`- **Recommended fix:** ${f.recommendation}`);
    if (f.reference) lines.push(`- **Reference:** ${f.reference}`);
    lines.push("");
  });

  const strengths = audit.findings.filter((f) => f.severity === "positive");
  if (strengths.length) {
    lines.push("## What's working");
    strengths.forEach((s) => lines.push(`- **${s.title}** — ${s.whyItMatters}`));
    lines.push("");
  }

  lines.push("## Accessibility checklist (WCAG 2.2)");
  audit.checklist.forEach((c) => {
    const mark = c.status === "pass" ? "✓" : c.status === "fail" ? "✗" : c.status === "warn" ? "!" : "–";
    lines.push(`- [${mark}] ${c.label}${c.wcag ? ` (WCAG ${c.wcag})` : ""} — ${c.detail}`);
  });
  lines.push("");

  lines.push("## Design system drift");
  audit.tokenIssues.forEach((t) => {
    lines.push(`- \`${t.token}\` (×${t.occurrences}): ${t.observed} → ${t.expected}. ${t.note}`);
  });
  lines.push("");

  lines.push("## Redesign direction");
  audit.redesign.forEach((r, i) => {
    lines.push(`### ${i + 1}. ${r.title}`);
    lines.push(r.summary);
    lines.push(`- Before: ${r.before.join("; ")}`);
    lines.push(`- After: ${r.after.join("; ")}`);
    lines.push("");
  });

  lines.push("---");
  lines.push("_Generated by UX Audit Lab._");
  return lines.join("\n");
}
